---
exclude: migrations|templates
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: double-quote-string-fixer

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        files: ^app/
        args:
          [
              -i,
              --remove-all-unused-imports,
              --ignore-init-module-imports,
              --expand-star-imports,
              --remove-duplicate-keys
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^app/
        args: [ --settings-file, app/pyproject.toml ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: ^app/
        language_version: python3
        args: [ "--config", "app/pyproject.toml" ]

  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit
        files: ^app/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        files: ^app/
        # args: [ --py39-plus, --py310-plus ]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        files: ^app/
        args: [ --config, app/.flake8 ]
        additional_dependencies:
          - flake8-cognitive-complexity
          # - flake8-comprehensions
          # - flake8-eradicate
          - flake8-debugger
          - flake8-quotes
          - flake8-expression-complexity
          - flake8-pie
          - flake8-string-format
          - flake8-typing-imports
          - flake8-plugin-utils
          - flake8-print
          - flake8-pytest
          - flake8-pytest-style
          - flake8-simplify
          - flake8-variables-names
          - flake8-commas
