# Generated by Django 4.2.7 on 2023-11-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_object_id', models.PositiveIntegerField(verbose_name='оригинал')),
                ('replacement_object_id', models.PositiveIntegerField(verbose_name='замена')),
                ('status', models.IntegerField(choices=[(1, 'Создан'), (2, 'Закончен успешно'), (3, 'Закончен с ошибкой')], default=1, verbose_name='статус обработки')),
                ('result', models.TextField(blank=True, null=True, verbose_name='результат')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='ошибки')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='таблица')),
            ],
            options={
                'verbose_name': 'обработка дубля',
                'verbose_name_plural': 'обработки дублей',
            },
        ),
    ]
